version: '3.8'

services:
  osm:
    image: devbuckit/osm:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - postgis
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASS: ${PG_PASS:-postgres}
      POSTGRES_DB: ${PG_DB:-osmgis}
      POSTGRES_HOST: postgis
    volumes:
      - osm-data:/data

  postgis:
    image: postgis/postgis:14-3.3  # Use a more recent and supported version
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASS:-postgres}  # Correct variable name
      POSTGRES_DB: ${PG_DB:-osmgis}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgis-data:
  osm-data:
